-- ================================================
-- Sistema de Consulta de Créditos ISSQN
-- Database: PostgreSQL
-- Autor: Ednilton Rauh
-- ================================================

-- ================================================
-- CRIAR USUÁRIO E DATABASE (se executando como postgres)
-- ================================================

-- Verificar e criar usuário
DO $$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'creditos_user') THEN
      CREATE USER creditos_user WITH PASSWORD 'creditos_pass';
END IF;
END
$$;

-- Verificar e criar database
SELECT 'CREATE DATABASE creditos_db OWNER creditos_user'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'creditos_db')\gexec

-- Garantir permissões
GRANT ALL PRIVILEGES ON DATABASE creditos_db TO creditos_user;

-- Conectar na database creditos_db
\c creditos_db creditos_user;

-- ================================================
-- CRIAR TABELA EXATAMENTE COMO NO PDF
-- ================================================

CREATE TABLE credito
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    numero_credito VARCHAR(50) NOT NULL,
    numero_nfse VARCHAR(50) NOT NULL,
    data_constituicao DATE NOT NULL,
    valor_issqn DECIMAL(15, 2) NOT NULL,
    tipo_credito VARCHAR(50) NOT NULL,
    simples_nacional BOOLEAN NOT NULL,
    aliquota DECIMAL(5, 2) NOT NULL,
    valor_faturado DECIMAL(15, 2) NOT NULL,
    valor_deducao DECIMAL(15, 2) NOT NULL,
    base_calculo DECIMAL(15, 2) NOT NULL,
    PRIMARY KEY (id)
);

-- Índices para otimização
CREATE INDEX IF NOT EXISTS idx_credito_numero_nfse ON credito(numero_nfse);
CREATE INDEX IF NOT EXISTS idx_credito_numero_credito ON credito(numero_credito);

-- ================================================
-- INSERIR DADOS EXATAMENTE COMO NO PDF
-- ================================================

INSERT INTO credito (numero_credito, numero_nfse, data_constituicao, valor_issqn,
                     tipo_credito, simples_nacional, aliquota, valor_faturado, valor_deducao, base_calculo)
VALUES
    ('123456', '7891011', '2024-02-25', 1500.75, 'ISSQN', true, 5.0, 30000.00, 5000.00, 25000.00),
    ('789012', '7891011', '2024-02-26', 1200.50, 'ISSQN', false, 4.5, 25000.00, 4000.00, 21000.00),
    ('654321', '1122334', '2024-01-15', 800.50, 'Outros', true, 3.5, 20000.00, 3000.00, 17000.00);

-- ================================================
-- GARANTIR PERMISSÕES PARA creditos_user
-- ================================================

GRANT ALL PRIVILEGES ON TABLE credito TO creditos_user;
GRANT ALL PRIVILEGES ON SEQUENCE credito_id_seq TO creditos_user;
GRANT USAGE ON SCHEMA public TO creditos_user;

-- ================================================
-- VERIFICAÇÕES FINAIS
-- ================================================

-- Mostrar dados inseridos
SELECT 'Database inicializado com sucesso! Créditos inseridos: ' || COUNT(*) as status
FROM credito;

-- Mostrar estrutura da tabela
\d credito

-- Mostrar todos os dados
SELECT
    numero_credito,
    numero_nfse,
    data_constituicao,
    valor_issqn,
    tipo_credito,
    CASE WHEN simples_nacional THEN 'Sim' ELSE 'Não' END as simples_nacional,
    aliquota,
    valor_faturado,
    valor_deducao,
    base_calculo
FROM credito
ORDER BY data_constituicao;